name = "stage5-site"
pages_build_output_dir = "./.vercel/output/static" 

compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_DOWNLOAD_URL = "https://downloads.stage5.tools/mac/latest/Translator.dmg"