export const REQUIRED_SHARED_STRING_KEYS = [
  "download",
  "downloadWindows",
  "homeDownloadRecommended",
  "homeDownloadChoose",
  "homeDownloadAllVersions",
  "footer",
  "copyright",
  "notFound",
  "goHome",
  "navVideoDownloader",
  "navSubtitleEditor",
  "navAiTranslation",
  "navPricing",
  "navFaq",
  "navAbout",
  "navContact",
  "navDownload",
  "footerProduct",
  "footerResources",
  "footerCompany",
  "footerLegal",
  "footerSupportedLanguages",
  "footerAboutStage5",
  "footerPrivacy",
  "footerTerms",
  "footerQuestions",
  "breadcrumbHome",
  "langSpanish",
  "langKorean",
  "langJapanese",
  "langChinese",
  "langFrench",
  "langGerman",
  "langPortuguese",
] as const;

export type RequiredSharedStringKey =
  (typeof REQUIRED_SHARED_STRING_KEYS)[number];
